#!/usr/bin/env python3
"""Generate retroarch.cfg implementing the AYN Thor starter guide settings.

Video settings baked in: Vulkan video driver (slang shaders), XMB menu @1.25x,
hotkey enable=Select, menu toggle=Select+X, exit=Select+Start, fast-forward=R2,
save state=Select+R1, load state=Select+L1, FPS toggle=Select+Y,
runahead toggle=Select+Right, quit confirmation off, autosave/autoload on,
system/BIOS directory pointed at the SD card.

Usage: python3 make_retroarch_cfg.py [sd-mount-or-staging]   (default ./sd_card)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent

CFG = """# auto-generated by ayn-automation :: make_retroarch_cfg.py
# settings mirror the AYN Thor Starter Guide (MetroGameCore)

# --- video / menu ---
video_driver = "vulkan"
video_gpu_record = "false"
menu_driver = "xmb"
materialui_menu_color_theme = "9"
menu_scale_factor = "1.250000"
fps_show = "false"

# --- hotkeys (RetroPad codes: 0=B 1=Y 2=Select 3=Start 4-7=Dpad 8=A 9=X 10=L1 11=R1 12=L2 13=R2 14=L3 15=R3) ---
input_hotkey_enable = "2"
input_menu_toggle = "9"
input_exit_emulator = "3"
input_hold_fast_forward = "13"
input_save_state = "11"
input_load_state = "10"
input_fps_toggle = "1"
input_runahead_toggle = "7"
quit_press_twice = "false"

# --- saving ---
savestate_auto_save = "true"
savestate_auto_load = "true"
config_save_on_exit = "true"

# --- directories (rewritten by deploy.sh to your actual SD label) ---
system_directory = "{bios_dir}"
"""

def main() -> int:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "sd_card"
    bios_dir = "/storage/emulated/0/ROMs/BIOS"  # placeholder; deploy.sh fixes it
    sd = target / "ROMs" / "BIOS"
    if target.exists() and sd.is_dir():
        # real card mounted on Mac: find its FAT volume id like /storage/0000-0000 later;
        # keep placeholder pattern but note staging path in comment
        pass
    out = target / "retroarch.cfg"
    out.write_text(CFG.format(bios_dir=bios_dir))
    print(f"✓ {out}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
